#--------------------------------------------
#   Name: Lynden Jones
#   ID: 1661689
#   CCID: lgjones
#   CMPUT 275, Winter 2022
#   Assignment 1 Navigation System: Part 2
#--------------------------------------------
run:
	gnome-terminal -- ./server/server
	python3 client/client.py

clean:
	rm -f inpipe outpipe